:toc:
:toc-placement!:
:toc-title!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= detect

CAUTION: Take heed that detection is not validation. If you give `detect` a string that is not a valid record id,
         it could incorrectly detect it. Do not rely on `detect` returning `undefined` for invalid record ids.
         Similarly do not assume `detect` not returning `undefined` means the record id is valid.

TIP: You can detect a database id without having set up `sierra-db-as-promised`.
     You can also detect an absolute API URL without having set up `SIERRA_API_HOST`.

toc::[]


== Synopsis

[source,js]
detect(id: Number | String) => RecordIdKind | undefined


== Examples

[source,js]
----
const { detect, RecordIdKind } = require('@sydneyunilibrary/sierra-record-id')

detect(undefined) // => undefined
detect('') // => undefined
detect('something random, but see the warning above!') // => undefined

detect(3696836) // => RecordIdKind.RECORD_NUMBER
detect('3696836') // => RecordIdKind.RECORD_NUMBER
detect('o369683') // => RecordIdKind.WEAK_RECORD_KEY
detect('i3696836') // => RecordIdKind.AMBIGUOUS_RECORD_KEY
detect('i36968367') // => RecordIdKind.STRONG_RECORD_KEY
detect('450975262916') // => RecordIdKind.DATABASE_ID
detect('v4/items/3696836') // => RecordIdKind.RELATIVE_V4_API_URL
detect('https://sierra.library.edu/iii/sierra-api/v4/items/3696836') // => RecordIdKind.ABSOLUTE_V4_API_URL
----

`detect` correctly detects record keys that have an initial period, for example `.o369683` and `.i36968367`. It also
correctly detects record ids for virtual records like `587634@abcde`, `i587634@abcde`, `.i5876345@abcde` and
`v4/items/587634@abcde`.


== Ambiguous record keys

Because record numbers can be 6 or 7 digits, `i3696836` is ambiguous. It could be a weak record key for the 7 digit
record number `3696836`, or it could be a strong key for the 6 digit record number `369683` with `6` being the check digit.

The previous paragraph notwithstanding, if the key for a 6 digit record number has an `x` check digit
(for example `o100007x`), `detect` will detect it as being strong and not as being ambiguous.


== Detecting a record ids's kind

`detect` detects the kind of the record id as follows (in order, after trimming whitespace):

. If the id starts with `.`, then it is a record key and `detect` calls `detectRecordKeyStrength`.
. If the id starts with `https://` and contains `/v4/`, then it is an absolute v4 API URL.
. If the id starts with `v4/`, then it is a relative v4 API URL.
. If the id starts with a letter, then it is a record key and `detect` calls `detectRecordKeyStrength`.
. If the id is a string 12 or more digits, then it is a database id.
. If the id starts with a digit, then it is a record number.
. Otherwise the kind of the record id is unknown.


=== Detecting the strength of a record key

`detectRecordKeyStrength` (which `detect` calls) detects the strength of a record key as follows:

. `detectRecordKeyStrength` strips that off any virtual record part (like `@abcde`), any initial period,
  and the record type character.
. If what's left ends in `x`, then the record key is strong.
. If what's left is a string of 6 digits, then the record key is weak.
. If what's left is a string of 7 digits, then the record key is ambiguous.
. If what's left is a string of 8 digits, then the record key is strong.
. Otherwise the record key is actually invalid.
